[2025-02-20T09:29:42.414+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T09:29:42.425+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process.Stage_songs scheduled__2025-02-20T08:00:00+00:00 [queued]>
[2025-02-20T09:29:42.431+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process.Stage_songs scheduled__2025-02-20T08:00:00+00:00 [queued]>
[2025-02-20T09:29:42.431+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-02-20T09:29:42.444+0000] {taskinstance.py:2889} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2025-02-20 08:00:00+00:00
[2025-02-20T09:29:42.450+0000] {logging_mixin.py:190} WARNING - /home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2583995) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-20T09:29:42.450+0000] {standard_task_runner.py:72} INFO - Started process 2584104 to run task
[2025-02-20T09:29:42.450+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_process', 'Stage_songs', 'scheduled__2025-02-20T08:00:00+00:00', '--job-id', '2171', '--raw', '--subdir', 'DAGS_FOLDER/project_etl.py', '--cfg-path', '/tmp/tmplgrpj2lt']
[2025-02-20T09:29:42.451+0000] {standard_task_runner.py:105} INFO - Job 2171: Subtask Stage_songs
[2025-02-20T09:29:42.484+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_process.Stage_songs scheduled__2025-02-20T08:00:00+00:00 [running]> on host teesta
[2025-02-20T09:29:42.537+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shubham' AIRFLOW_CTX_DAG_ID='etl_process' AIRFLOW_CTX_TASK_ID='Stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-20T08:00:00+00:00'
[2025-02-20T09:29:42.538+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-20T09:29:42.544+0000] {base.py:84} INFO - Retrieving connection 'aws_credentials'
[2025-02-20T09:29:42.545+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2025-02-20T09:29:42.553+0000] {stage_redshift.py:50} INFO - Clearing data from Redshift table staging_songs
[2025-02-20T09:29:42.556+0000] {base.py:84} INFO - Retrieving connection 'redshift'
[2025-02-20T09:29:44.273+0000] {sql.py:553} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2025-02-20T09:29:44.777+0000] {sql.py:562} INFO - Rows affected: 0
[2025-02-20T09:29:45.610+0000] {stage_redshift.py:53} INFO - Copying data from S3 to Redshift table staging_songs
[2025-02-20T09:29:45.611+0000] {stage_redshift.py:80} INFO - Executing COPY command on Redshift...
[2025-02-20T09:29:47.432+0000] {sql.py:553} INFO - Running statement: 
            COPY staging_songs
            FROM 's3://udacity-dend/song_data'
            ACCESS_KEY_ID 'AKIAUPR77A3AITXAUGOM'
            SECRET_ACCESS_KEY '***'
            REGION 'us-west-2'
            TIMEFORMAT as 'epochmillisecs'
            FORMAT AS JSON 's3://udacity-dend/auto'
        , parameters: None
[2025-02-20T09:29:56.503+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    format_options=format_options
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: Problem reading manifest file - S3ServiceException:The specified key does not exist.,Status 404,Error NoSuchKey,Rid QZXVS9NDBWWR7A2J,ExtRid aSh1EhqClNTaz8b/UqxrAU8o7ZMwxCHeNzhoQpMQxLkTqiiQiOfAO/vmwZJZbekcdwDbagZmAFs=,CanRetry 1
DETAIL:  
  -----------------------------------------------
  error:  Problem reading manifest file - S3ServiceException:The specified key does not exist.,Status 404,Error NoSuchKey,Rid QZXVS9NDBWWR7A2J,ExtRid aSh1EhqClNTaz8b/UqxrAU8o7ZMwxCHeNzhoQpMQxLkTqiiQiOfAO/vmwZJZbekcdwDbagZmAFs=,CanRetry 1
  code:      8001
  context:   s3://udacity-dend/auto
  query:     208247[child_sequence:1]
  location:  s3_utility.cpp:384
  process:   padbmaster [pid=1073873032]
  -----------------------------------------------


[2025-02-20T09:29:56.511+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_process, task_id=Stage_songs, run_id=scheduled__2025-02-20T08:00:00+00:00, execution_date=20250220T080000, start_date=20250220T092942, end_date=20250220T092956
[2025-02-20T09:29:56.524+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-20T09:29:56.525+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2171 for task Stage_songs (Problem reading manifest file - S3ServiceException:The specified key does not exist.,Status 404,Error NoSuchKey,Rid QZXVS9NDBWWR7A2J,ExtRid aSh1EhqClNTaz8b/UqxrAU8o7ZMwxCHeNzhoQpMQxLkTqiiQiOfAO/vmwZJZbekcdwDbagZmAFs=,CanRetry 1
DETAIL:  
  -----------------------------------------------
  error:  Problem reading manifest file - S3ServiceException:The specified key does not exist.,Status 404,Error NoSuchKey,Rid QZXVS9NDBWWR7A2J,ExtRid aSh1EhqClNTaz8b/UqxrAU8o7ZMwxCHeNzhoQpMQxLkTqiiQiOfAO/vmwZJZbekcdwDbagZmAFs=,CanRetry 1
  code:      8001
  context:   s3://udacity-dend/auto
  query:     208247[child_sequence:1]
  location:  s3_utility.cpp:384
  process:   padbmaster [pid=1073873032]
  -----------------------------------------------

; 2584104)
Traceback (most recent call last):
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    format_options=format_options
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: Problem reading manifest file - S3ServiceException:The specified key does not exist.,Status 404,Error NoSuchKey,Rid QZXVS9NDBWWR7A2J,ExtRid aSh1EhqClNTaz8b/UqxrAU8o7ZMwxCHeNzhoQpMQxLkTqiiQiOfAO/vmwZJZbekcdwDbagZmAFs=,CanRetry 1
DETAIL:  
  -----------------------------------------------
  error:  Problem reading manifest file - S3ServiceException:The specified key does not exist.,Status 404,Error NoSuchKey,Rid QZXVS9NDBWWR7A2J,ExtRid aSh1EhqClNTaz8b/UqxrAU8o7ZMwxCHeNzhoQpMQxLkTqiiQiOfAO/vmwZJZbekcdwDbagZmAFs=,CanRetry 1
  code:      8001
  context:   s3://udacity-dend/auto
  query:     208247[child_sequence:1]
  location:  s3_utility.cpp:384
  process:   padbmaster [pid=1073873032]
  -----------------------------------------------


[2025-02-20T09:29:56.541+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T09:29:56.557+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T09:29:56.557+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
