[2025-02-20T08:52:56.162+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T08:52:56.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_tables_dag.create_users_table manual__2025-02-20T08:52:33.272398+00:00 [queued]>
[2025-02-20T08:52:56.183+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_tables_dag.create_users_table manual__2025-02-20T08:52:33.272398+00:00 [queued]>
[2025-02-20T08:52:56.183+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-20T08:52:56.199+0000] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): create_users_table> on 2025-02-20 08:52:33.272398+00:00
[2025-02-20T08:52:56.205+0000] {logging_mixin.py:190} WARNING - /home/teesta/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=860500) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-20T08:52:56.206+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'create_tables_dag', 'create_users_table', 'manual__2025-02-20T08:52:33.272398+00:00', '--job-id', '2116', '--raw', '--subdir', 'DAGS_FOLDER/create_tables_dag.py', '--cfg-path', '/tmp/tmpizizi22g']
[2025-02-20T08:52:56.206+0000] {standard_task_runner.py:105} INFO - Job 2116: Subtask create_users_table
[2025-02-20T08:52:56.207+0000] {standard_task_runner.py:72} INFO - Started process 860675 to run task
[2025-02-20T08:52:56.238+0000] {task_command.py:467} INFO - Running <TaskInstance: create_tables_dag.create_users_table manual__2025-02-20T08:52:33.272398+00:00 [running]> on host teesta
[2025-02-20T08:52:56.304+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_tables_dag' AIRFLOW_CTX_TASK_ID='create_users_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T08:52:33.272398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T08:52:33.272398+00:00'
[2025-02-20T08:52:56.305+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-20T08:52:56.319+0000] {sql.py:278} INFO - Executing: 
CREATE TABLE public.users (
	userid int4 NOT NULL,
	first_name varchar(256),
	last_name varchar(256),
	gender varchar(256),
	"level" varchar(256),
	CONSTRAINT users_pkey PRIMARY KEY (userid)
);
[2025-02-20T08:52:56.324+0000] {base.py:84} INFO - Retrieving connection 'redshift'
[2025-02-20T08:52:56.472+0000] {base.py:84} INFO - Retrieving connection 'redshift'
[2025-02-20T08:52:58.071+0000] {sql.py:553} INFO - Running statement: 
CREATE TABLE public.users (
	userid int4 NOT NULL,
	first_name varchar(256),
	last_name varchar(256),
	gender varchar(256),
	"level" varchar(256),
	CONSTRAINT users_pkey PRIMARY KEY (userid)
);, parameters: None
[2025-02-20T08:53:00.515+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-20T08:53:00.516+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_tables_dag, task_id=create_users_table, run_id=manual__2025-02-20T08:52:33.272398+00:00, execution_date=20250220T085233, start_date=20250220T085256, end_date=20250220T085300
[2025-02-20T08:53:00.550+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T08:53:00.568+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-20T08:53:00.572+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
